### ISSUE TITLE
More detailed wireframes

### ISSUE THREAD

**Issue by rglassett** [eltonc88/db-alpha#1]
You've only got three wireframes, but it looks like both CompanyShow and PostShow will have to be CompositeViews. You'll want to do wireframes to plan at least the following views:
- RSSFeed
- RSSFeedItem
- TwitterFeed
- TwitterFeedItem
- PostForm
- CompaniesIndex
- NavBar

**Comment by eltonc8** [comment]
Uploaded a new company view.
Will consider a suggestion of a CompaniesIndex for bonus phase (had not thought about how this would look, as I had assumed that users will search for such a company [too many to list in real life]).
Thanks!

**Comment by rglassett** [comment]
CompaniesIndex doesn't have to show all the companies; in Backbone, an Index view is just a view that is passed/listens to a collection. :)
