### ISSUE TITLE
Schema issues

### ISSUE THREAD

**Issue by rglassett** [eltonc88/db-alpha#2]
Posts should have a `text` body, not a `string` (which is capped at 255 characters)

Post taggings should have columns for `tag_id` and `post_id`. There should also be a table for `tags`.

You need a `users` table.

The `companies` table needs columns for `rss_feed_url` and `twitter_url`

**Comment by eltonc8** [comment]
Updated with suggestions. Thanks!

Except for twitter_url, which can be inferred from stock symbol, and rss_feed_url, for which I am not sure if company-specific rss feed exists.
